repos:
  # bandit - 安全检查
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        exclude: ^tests/
        additional_dependencies: ["bandit[toml]"]

  # ruff - lint + format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.6.9'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

